### ISSUE TITLE
"realm.close" is not a function - Node-CLI

### ISSUE THREAD

**Issue by arjunpola** [mongodb-university/realm-tutorial#66]
I was able to successfully run the Node-CLI project after modifying the credentials and was also able to view my data being synced in web console.

But on selecting the "Log Out" option from the project menu in terminal, I get the below error.

<img width="318" alt="Screenshot 2020-09-09 at 5 50 58 PM" src="https://user-images.githubusercontent.com/4324936/92597981-c1ac6000-f2c5-11ea-96f7-3a261dd0d9aa.png">

Tested on
OS:  macOS Catalina (ver 10.15.6)
Node Version: v12.18.1
NPM Version: 6.14.5

**Comment by MongoCaleb** [comment]
Thanks @arjunpola! I've got a PR (https://github.com/mongodb-university/realm-tutorial/pull/68) in now to fix this. Should be merged in soon!

**Comment by arjunpola** [comment]
Verified the fix after upgrading the project to use **realm@^10.0.0-beta.13**

**Comment by arjunpola** [comment]
> Thanks @arjunpola! I've got a PR (#68) in now to fix this. Should be merged in soon!

Thank you for the fix @MongoCaleb  :)
