### ISSUE TITLE
Unresolved Reference: emailPasswordAuth in LoginActivity.kt

### ISSUE THREAD

**Issue by jtcoyle** [mongodb-university/realm-tutorial#82]
I am not sure if this is the place to report this but, the Task Tracker tutorial for Android with Kotlin is using an Unresolved Reference (emailPasswordAuth) used in the model file, loginActivity.kt (lines 68 and 82).  The code here on GitHub has been corrected to use emailPassword.

It would be nice if the tutorial could also be corrected.

Regards,

Joe

**Comment by nathan-contino-mongo** [comment]
Thanks for bringing this to my attention, Joe -- I've created a PR in our Realm documentation to fix this issue. Looks like we missed one occurrence of `emailPasswordAuth` in the tutorial when we ported everything over to beta 8. We've actually got some new tutorials landing soon that will make this an issue of the past (automating the generation of code snippets) so hopefully this won't happen again!

Fix PR: https://github.com/mongodb/docs-realm/pull/510
